### ISSUE TITLE
About loading model

### ISSUE THREAD

**Issue by hoho303** [mlzxy/devit#11]
Hello! Thanks for your great work!

I would like to ask a question about the resources required to load your model. How much VRAM do I need to load the model using the GPU?

**Comment by mlzxy** [comment]
I don't have an accurate estimation. But I guess if K=3, then a 3090 24 GB would be already to load and run it. If you only need to run on a few images, using CPU would be an OK choice.

**Comment by hoho303** [comment]
Thank you for your answer!
