### ISSUE TITLE
gdown falils to download data and checkpoints

### ISSUE THREAD

**Issue by Godofnothing** [mlzxy/devit#12]
Thanks for a great work!

When trying to download the data and checkpoints via `gdown` I encountered the following problem:

> Access denied with the following error:
> 
>         Too many users have viewed or downloaded this file recently. Please
>         try accessing the file again later. If the file you are trying to
>         access is particularly large or is shared with many people, it may
>         take up to 24 hours to be able to view or download the file. If you
>         still can't access a file after 24 hours, contact your domain
>         administrator.
> 
> You may still be able to access the file from the browser:
> 
>          https://drive.google.com/uc?id=1khS5sVsi6e4yOI9O8U0PVPk-B3mZ7C8l

I've tried several times, but the same message arose. Probably, one can somehow configure option of unlimited downloads in the drive?

**Comment by theodu** [comment]
You can either download it from the Google drive UI, or if you want to download it with a script, the answer from the author in #7, with rclone worked for me.

**Comment by Godofnothing** [comment]
@theodu  I see, thanks for the advice!
