### ISSUE TITLE
Training Resources Question

### ISSUE THREAD

**Issue by jackboyla** [mlzxy/devit#18]
Hi, this is really great work and thank you for sharing!

Just a question about training resources - do you know roughly how long it took to train the models ViT-s/b/l backbones and with what GPUs?

**Comment by mlzxy** [comment]
Hi, @jackboyla 

I am using 4 A100 40GB for training with the given config and `K=10`.  (`K` is the number of classes from class preselection). 

Note that the parameter `K` greatly affects memory consumption and speed. As I later found that using `K=3` produces a very close accuracy. So I guess training with `K=3` also works. In that case, I believe `K=3` shall be trainable with 4 x 3090 24G at least for COCO (without the segmentation branch).   For LVIS, the segmentation branch can also be trained separately (by freezing detection and classification).
