### ISSUE TITLE
How to inference my own data

### ISSUE THREAD

**Issue by JeremyLin886** [mlzxy/devit#19]
Hi, it's a great job. I want to use this work to perform open vocabulary object detection **on my own data**, what should I do? For example, how do I prepare the **class_base.pth and class_novel.pth** files? Thanks！

**Comment by mlzxy** [comment]
I suggest the starting point could be the demo I provided. You could check my previous answer in #5. Hope it helps.

**Comment by JeremyLin886** [comment]
It works. Thanks！
