### ISSUE TITLE
Run pretrained model on custom data

### ISSUE THREAD

**Issue by MaxTeselkin** [mlzxy/devit#5]
Hi! Thanks for interesting work. I want to test your nn architecture on custom data (I am going to use a pretrained model).
As far as I understood, to run pretrained model on custom data I need to do the following:

- prepare 10-30 reference images labeled with masks and bounding boxes (masks are needed in order to create category space as shown in demo, right?) and create a .pth file with class prototypes
- load pretrained weights into the model and pass input data with category space to it

After completing the steps above I will be able to use it as an object detector to detect objects presented in category space?

**Comment by mlzxy** [comment]
Yes, in fact the demo in this repo would be a good example. 

For the annotation part, I use https://github.com/uncbiag/SimpleClick (v1.0 branch). It is extremely easy to annotate instance masks with this tool. The rest of the procedure will be very similar to the demo I provided, including the notebook that extracts prototypes (category space) and the inference part where the category space get swapped.

**Comment by MaxTeselkin** [comment]
Thanks for clarifying
