### ISSUE TITLE
the class of background prototype

### ISSUE THREAD

**Issue by eternaldolphin** [mlzxy/devit#6]
![7d7b5edcb9f5dcfddcaad35874db4b3](https://github.com/mlzxy/devit/assets/55774463/724d1d2d-3487-454f-a708-c51718ba254a)
I did not find the coco_2017_train_panoptic_stuffonly in detectron2/data/datasets/builtin.py
![image](https://github.com/mlzxy/devit/assets/55774463/1d847a90-3cfd-45fc-b7db-0ab567ae9379)
is it means all classes in above annotations

**Comment by mlzxy** [comment]
This `coco_2017_train_panoptic_stuffonly` dataset shall be a builtin one in detectron, like [here](https://github.com/facebookresearch/detectron2/blob/main/configs/Misc/semantic_R_50_FPN_1x.yaml). I use the stuff classes, e.g. sky, road. 

Consider preparing this dataset from the instructions of https://detectron2.readthedocs.io/en/latest/tutorials/builtin_datasets.html?highlight=dataset#expected-dataset-structure-for-panopticfpn .
