### ISSUE TITLE
Feature Subspace Projection

### ISSUE THREAD

**Issue by ZhouHongLiang6** [mlzxy/devit#65]
Hi @mlzxy ,

I'm having another issue. I couldn't find any code related to Feature Subspace Projection in the `devit/lib/regionprop_update.py` file. Could you please guide me on where this code is located in the project?

Many Thanks,

Best,

**Comment by mlzxy** [comment]
Hi,

Please check
https://github.com/mlzxy/devit/blob/1de0fcf9d03e731ef4bbe96bd7d33f2acf75c7d6/detectron2/modeling/meta_arch/devit_update.py#L706C1-L706C9
.

Starting from line 706, it first computes the dot product between features
and prototypes, and then shuffle them. The shuffle part code may be a
little obscure.


Best,
Xinyu

**Comment by ZhouHongLiang6** [comment]
Hi,

Thank you for your patience.

Best,
Hongliang
